name: Deploy Bicep Template

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Log in to Azure
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Step 3: Deploy the Bicep template
      - name: Deploy Bicep Template
        run: |
          az deployment group create \
            --resource-group myTestRG \
            --template-file DomainController/main.bicep \
            --parameters adminUsername=${{ secrets.ADMIN_USERNAME }} adminPassword=${{ secrets.ADMIN_PASSWORD }} safeModePassword=${{ secrets.SAFE_MODE_PASSWORD }}